# Ignition Gateway Network Example
---
x-ignition-common: &ignition-common
  image: kcollins/ignition:latest  # You can [and should] change `latest` to a specific version, e.g. `8.1.22`
  pull_policy: always  # feel free to comment this out if you change from the `latest` tag

services:
  hub:
    <<: [*ignition-common]
    ports:
      - "8088:8088"
    volumes:
      # - ./gateway_backup.gwbk:/restore.gwbk
      - hub-data:/var/lib/ignition/data
    environment:
      GATEWAY_SYSTEM_NAME: hub
      GATEWAY_ADMIN_PASSWORD: password
      GATEWAY_NETWORK_AUTOACCEPT_DELAY: 120
      GATEWAY_MODULES_ENABLED: vision,perspective,opc-ua,tag-historian,logix-driver

  spoke1:
    <<: [*ignition-common]
    ports:
      - "8089:8088"
    volumes:
      # - ./gateway_backup.gwbk:/restore.gwbk
      - spoke1-data:/var/lib/ignition/data
    environment:
      GATEWAY_SYSTEM_NAME: spoke1
      GATEWAY_ADMIN_PASSWORD: password
      GATEWAY_NETWORK_0_HOST: hub
      GATEWAY_MODULES_ENABLED: vision,opc-ua,logix-driver

  spoke2:
    image: kcollins/ignition:latest
    ports:
      - "8090:8088"
    volumes:
      - spoke2-data:/var/lib/ignition/data
    environment:
      GATEWAY_SYSTEM_NAME: spoke2
      GATEWAY_ADMIN_PASSWORD: password
      GATEWAY_NETWORK_0_HOST: hub
      GATEWAY_MODULES_ENABLED: vision,opc-ua,logix-driver
      IGNITION_EDITION: edge

volumes:
  hub-data:
  spoke1-data:
  spoke2-data: